### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mil7on228** [AurasV/Audio-Converter#1]
How can I convert multiple files?

**Comment by AurasV** [comment]
I didn't think about it when I created it, I'm finishing that functionality now, should be up in a few minutes

**Comment by AurasV** [comment]
> I didn't think about it when I created it, I'm finishing that functionality now, should be up in a few minutes

I updated the repository now, when the file dialog opens you can select multiple files using CTRL + Click / SHIFT + Click
